name: flutter_credit_card
description: A Credit Card widget package, support entering card details, card flip animation.
version: 5.0.0
homepage: https://github.com/appu-sm/financemanager_creditcard
issue_tracker: https://github.com/appu-sm/financemanager_creditcard/issues

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - icons/
  fonts:
    - family: halter
      fonts:
        - asset: font/halter.ttf
